#' Synthetic vaccination coverage survey (mapped)
#'
#' A fully synthetic household vaccination coverage survey, already mapped onto
#' vaxsurvR's standardised concepts. It is generated by
#' `data-raw/make_vcs_example.R` and contains no real participant data of any
#' kind.
#'
#' The simulated design is a two-stage cluster sample: 30 PSUs stratified into
#' urban and rural, 20 households screened per PSU, and children aged 12--23
#' months enumerated in consenting eligible households. Coverage declines along
#' the schedule and is lower in rural strata, so dropout indicators are
#' non-trivial.
#'
#' @section Planted data-quality problems:
#' The generator deliberately injects the problems below so that the `check_*()`
#' functions have something to find. `vcs_example$meta$planted_issues` lists the
#' affected interview identifiers.
#'
#' \describe{
#'   \item{`duplicate_child_id`}{the same child identifier in two households}
#'   \item{`prebirth`}{a dose dated before the child's date of birth}
#'   \item{`out_of_sequence`}{PENTA2 dated before PENTA1}
#'   \item{`short_interval`}{PENTA1 to PENTA2 in 3 days}
#'   \item{`future_date`}{a dose dated after the interview}
#'   \item{`duplicate_dose`}{two doses of one antigen sharing a date}
#'   \item{`date_without_card`}{card dates recorded although no card was seen}
#'   \item{`duplicate_gps`}{several households sharing one GPS point}
#'   \item{`short_interview`}{interviews of 2--6 minutes}
#'   \item{`unparseable_date`}{"31/02/2025" and free text in a date field}
#'   \item{`age_out_of_window`}{a child well outside 12--23 months}
#'   \item{`ineligible_with_child`}{a household screened ineligible with a
#'     completed child module}
#' }
#'
#' Partial dates (year-month only) and missing cards occur naturally in the
#' simulation rather than being planted.
#'
#' @format A [vcs_data][new_vcs_data] object with 600 households, 256 children
#'   and 3,584 child-vaccine rows.
#' @source Simulated; see `data-raw/make_vcs_example.R`.
#' @seealso [vcs_example_raw], [vcs_example_dictionary], [vcs_example_schedule]
#' @examples
#' vcs_example
#' summary(vcs_example)
#' names(vcs_example$meta$planted_issues)
"vcs_example"

#' Synthetic vaccination coverage survey (raw wide export)
#'
#' The unmapped wide export behind [vcs_example], in the shape a mobile
#' data-collection platform produces: one row per interview, repeat groups
#' encoded in column names, everything stored as text. Use it to demonstrate
#' [map_vcs_variables()] and the de-identification module, which needs the
#' direct identifiers this table still carries.
#'
#' All names, telephone numbers, addresses and coordinates are fabricated.
#'
#' @format A tibble with 600 rows and 190 columns.
#' @source Simulated; see `data-raw/make_vcs_example.R`.
#' @seealso [vcs_example]
#' @examples
#' dim(vcs_example_raw)
#' vcs_example_raw[1:3, c("KEY", "psu_id", "stratum", "final_weight")]
"vcs_example_raw"

#' Dictionary mapping the synthetic example export
#'
#' @format A [vcs_dictionary()].
#' @source Simulated; see `data-raw/make_vcs_example.R`.
#' @seealso [vcs_example_raw]
#' @examples
#' vcs_example_dictionary
"vcs_example_dictionary"

#' Vaccination schedule used by the synthetic example
#'
#' A fourteen-dose infant schedule covering BCG, OPV, PENTA, PCV, IPV, MCV and
#' yellow fever. It is illustrative: adapt it to the national EPI calendar
#' before analysing a real survey.
#'
#' @format A [vcs_schedule()] with 14 rows.
#' @source Simulated; see `data-raw/make_vcs_example.R`.
#' @examples
#' vcs_example_schedule
"vcs_example_schedule"
